"""Add user_id allowing nulls

Revision ID: 1188905b2a02
Revises: 6de76eb17056
Create Date: 2026-06-22 00:21:01.396666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1188905b2a02'
down_revision: Union[str, Sequence[str], None] = '6de76eb17056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'research_tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'research_tasks', type_='foreignkey')
    op.drop_column('research_tasks', 'user_id')
    # ### end Alembic commands ###
