"""Add research_tasks table with JSONB

Revision ID: 6de76eb17056
Revises: fb0ad0d47235
Create Date: 2026-06-19 01:38:02.233517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6de76eb17056'
down_revision: Union[str, Sequence[str], None] = 'fb0ad0d47235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_tasks_id'), 'research_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_research_tasks_topic'), 'research_tasks', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_tasks_topic'), table_name='research_tasks')
    op.drop_index(op.f('ix_research_tasks_id'), table_name='research_tasks')
    op.drop_table('research_tasks')
    # ### end Alembic commands ###
